version: '3.8'
services:
  site:
    image: "blog-project:latest"
    restart: "no"
    networks:
      - blog-network
    ports:
      - "${PORT_TO_USE:-8080}:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/usr/share/nginx/blog-project
    working_dir: /usr/share/nginx/blog-project

  postgres:
    image: postgres:15.0-alpine
    restart: "always"
    environment:
      POSTGRES_USER: blog-project
      POSTGRES_PASSWORD: NotVerySecure123
      POSTGRES_DB: blog
    networks:
      blog-network:
        aliases:
          - database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    restart: always
    networks:
      blog-network:
        aliases:
          - redis


networks:
  blog-network:
